spring:
  datasource:
    url: jdbc:mysql://localhost:3360/pam
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: pam
  data:
    rest:
      base-path: pam/
server:
  port: 8081
